// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkyBooker.BookingService.Context;

#nullable disable

namespace SkyBooker.BookingService.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260421111317_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkyBooker.BookingService.Entities.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("text")
                        .HasColumnName("booking_id");

                    b.Property<decimal>("AncillaryCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ancillary_cost");

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_fare");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer")
                        .HasColumnName("flight_id");

                    b.Property<int>("LuggageKg")
                        .HasColumnType("integer")
                        .HasColumnName("luggage_kg");

                    b.Property<string>("MealPreference")
                        .HasColumnType("text")
                        .HasColumnName("meal_preference");

                    b.Property<string>("PaymentId")
                        .HasColumnType("text")
                        .HasColumnName("payment_id");

                    b.Property<string>("PnrCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pnr_code");

                    b.Property<int?>("ReturnFlightId")
                        .HasColumnType("integer")
                        .HasColumnName("return_flight_id");

                    b.Property<string>("SeatIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_ids");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("taxes");

                    b.Property<decimal>("TotalFare")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_fare");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PnrCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
