// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkyBooker.SeatService.Context;

#nullable disable

namespace SkyBooker.SeatService.Migrations
{
    [DbContext(typeof(SeatDbContext))]
    [Migration("20260421071400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkyBooker.SeatService.Entities.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("seat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeatId"));

                    b.Property<string>("Column")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("column");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer")
                        .HasColumnName("flight_id");

                    b.Property<bool>("HasExtraLegroom")
                        .HasColumnType("boolean")
                        .HasColumnName("has_extra_legroom");

                    b.Property<int?>("HeldByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("held_by_user_id");

                    b.Property<DateTime?>("HeldSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("held_since");

                    b.Property<bool>("IsAisle")
                        .HasColumnType("boolean")
                        .HasColumnName("is_aisle");

                    b.Property<bool>("IsWindow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_window");

                    b.Property<decimal>("PriceMultiplier")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("price_multiplier");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<string>("SeatClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_class");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_number");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("SeatId");

                    b.HasIndex("FlightId", "SeatClass");

                    b.HasIndex("FlightId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("seats");
                });
#pragma warning restore 612, 618
        }
    }
}
